-- +goose Up
-- +goose StatementBegin
INSERT INTO settings (name) VALUES ('SMTP_HOST');
INSERT INTO settings (name) VALUES ('SMTP_PORT');
INSERT INTO settings (name) VALUES ('SMTP_USER');
INSERT INTO settings (name) VALUES ('SMTP_PASSWORD');
INSERT INTO settings (name) VALUES ('SMTP_SENDER');

INSERT INTO settings (name) VALUES ('EMAIL_VERIFICATION_SUBJECT');
INSERT INTO settings (name) VALUES ('EMAIL_VERIFICATION_REDIRECT_URL');
INSERT INTO settings (name) VALUES ('EMAIL_VERIFICATION_BODY');

INSERT INTO settings (name) VALUES ('PASSWORD_RESET_SUBJECT');
INSERT INTO settings (name) VALUES ('PASSWORD_RESET_REDIRECT_URL');
INSERT INTO settings (name) VALUES ('PASSWORD_RESET_BODY');


INSERT INTO settings (name) VALUES ('MFA_VERIFICATION_SUBJECT');
INSERT INTO settings (name) VALUES ('MFA_VERIFICATION_REDIRECT_URL');
INSERT INTO settings (name) VALUES ('MFA_VERIFICATION_BODY');

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM settings WHERE name = 'SMTP_HOST';
DELETE FROM settings WHERE name = 'SMTP_PORT';
DELETE FROM settings WHERE name = 'SMTP_USER';
DELETE FROM settings WHERE name = 'SMTP_PASSWORD';
DELETE FROM settings WHERE name = 'SMTP_SENDER';

DELETE FROM settings WHERE name = 'EMAIL_VERIFICATION_SUBJECT';
DELETE FROM settings WHERE name = 'EMAIL_VERIFICATION_REDIRECT_URL';
DELETE FROM settings WHERE name = 'EMAIL_VERIFICATION_BODY';

DELETE FROM settings WHERE name = 'PASSWORD_RESET_SUBJECT';
DELETE FROM settings WHERE name = 'PASSWORD_RESET_REDIRECT_URL';
DELETE FROM settings WHERE name = 'PASSWORD_RESET_BODY';

DELETE FROM settings WHERE name = 'MFA_VERIFICATION_SUBJECT';
DELETE FROM settings WHERE name = 'MFA_VERIFICATION_REDIRECT_URL';
DELETE FROM settings WHERE name = 'MFA_VERIFICATION_BODY';

-- +goose StatementEnd
